# Generated by Django 2.2.13 on 2020-12-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201227_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='registeredStudents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.CharField(max_length=200),
        ),
    ]
